In [56]:
s= set()
print (s)
print (type(s))

s1 ={1,3,2,5,4,1,5,3,(1,2)}
print (s1)
print (type(s1))

s1={1,"Farooq",2.5,True } # TRUE is equal 1 
print (s1)
print (type(s1))


fruit=  ["apple","banana","mango"]
print(fruit)
print (type(fruit))
fruit= set( ["apple","banana","mango"])
print(fruit)
print (type(fruit))

s1 = {1,2,3,4}
s2 = {5,3,2,1}
s1==s2
s1.add(5)
s1.update([8,6,7])
#s1.update({"Imran"})
#s1.update("Imran")
#s1.update(set("Imran"))
s1.update(["Imran"])
print (s1)
w=s1.pop()
print(w)
print(s1)


#s1 = set("Imran")
#print (s1)

print (s1)
w=s1.remove(8)
s1.discard("Imran")
print (w)
print (s1)


s1 = {1,2,3,4}
s2 = {5,3,2,1}

#Union ||
#Intersection &
#Difference - 
#symmetric difference
s3=s1| s2
print (s3)
s3 = s1 & s2
print (s3)
s3 = s1 - s2
print (s3)

s3 = s1 ^ s2
print (s3)

set()
<class 'set'>
{1, 2, 3, 4, 5, (1, 2)}
<class 'set'>
{1, 'Farooq', 2.5}
<class 'set'>
['apple', 'banana', 'mango']
<class 'list'>
{'mango', 'banana', 'apple'}
<class 'set'>
{1, 2, 3, 4, 5, 6, 7, 8, 'Imran'}
1
{2, 3, 4, 5, 6, 7, 8, 'Imran'}
{2, 3, 4, 5, 6, 7, 8, 'Imran'}
None
{2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5}
{1, 2, 3}
{4}
{4, 5}